# Vectores

El presente notebook contiene notas del bootcamp de ML de Código Facilito.

## ¿Qué es un vector?


Un vector es una estructura de datos lineal que contiene elementos de un mismo tipo. En programación, los vectores son similares a los arrays, pero con algunas diferencias clave.

In [2]:
import numpy as np  # Importar librerías

In [3]:
# Creación de un vector
vector = np.array([2, 3])
print("Vector:", vector)

Vector: [2 3]


## ¿Qué es un espacio vectorial?

Un espacio vectorial $V$ necesita cumplir las siguientes características para cualquier $u, v, w \in V$:
- **Propiedad asociativa:** $$(u+v)+w=u+(v+w)$$
- **Propiedad conmutativa:** $$u+v=v+u$$
- **Propiedad distributiva:** Si $c\in\mathbb{R}$, $$c(u+v)=cu+cv$$
- **Existencia de elemento neutro:** Existe un $0$ tal que $$0+u=u+0=u$$ para todo $u \in V$
- **Existencia del elemento inverso:** Dado un $u \in V$, existe un $-u \in V$ tal que $$u+(-u)=0$$
- **Existencia del elemento neutro:** Dado un $u \in V$, existe un $1 \in V$ tal que $$1 \cdot u = u$$

In [8]:
# Espacio vectorial en 2D
v1 = np.array([1, 2])
v2 = np.array([3, 4])
v3 = np.array([-1, 0])
u1 = np.array([4, -1, 2])

## Operaciones básicas sobre vectores: suma y multiplicación


In [9]:
# Suma de vectores
result_sum = (
    v1 + v2
)  # Suma de vectores, si los vectores no tienen la misma dimensión, se produce un error.
print("Suma de v1 y v2:", result_sum)

Suma de v1 y v2: [4 6]


In [10]:
# Multiplicación por escalar
scalar = 2
result_scalar = scalar * v1  # Multiplicación por escalar 2
print("Multiplicación por escalar:", result_scalar)

Multiplicación por escalar: [2 4]


## Normas en vectores

In [12]:
# vector = np.array([2, 3])
# La norma de un vector es una medida de su longitud o tamaño.

# Norma euclidiana o L2
norm_l2 = np.linalg.norm(vector)
print("Norma L2 del vector:", norm_l2)

# Norma taxicab o L1
norm_l1 = np.linalg.norm(vector, ord=1)
print("Norma L1 del vector:", norm_l1)

Norma L2 del vector: 3.605551275463989
Norma L1 del vector: 5.0


## Producto interno o producto escalar

In [13]:
# Producto interno de dos vectores
# v1 = np.array([1, 2])
v4 = np.array([2, 4])
dot_product = np.dot(v1, v4)  # Producto interno entre v1 y v4
print("Producto interno entre v1 y v4:", dot_product)

Producto interno entre v1 y v4: 10


# Matrices

## Bases del álgebra matricial (álgebra lineal)

In [14]:
# Crear una matriz
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Matriz de 3x3
print("Matriz:")
print(matriz)

Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


 ### Suma y multiplicación por un escalar

In [15]:
# Crear dos matrices
matriz1 = np.array([[1, 2, 3], [4, -5, 6], [7, 8, 9]])
matriz2 = np.array([[2, 4, -1], [-2, 5, 3], [7, -2, -1]])

# Suma de matrices
resultado = matriz1 + matriz2
print("Matriz 1:")
print(matriz1)
print("Matriz 2:")
print(matriz2)
print("Suma de Matrices:")
print(resultado)

Matriz 1:
[[ 1  2  3]
 [ 4 -5  6]
 [ 7  8  9]]
Matriz 2:
[[ 2  4 -1]
 [-2  5  3]
 [ 7 -2 -1]]
Suma de Matrices:
[[ 3  6  2]
 [ 2  0  9]
 [14  6  8]]


### Multiplicación entre matrices y vectores

In [18]:
# Multiplicación de matriz por vector
matrix = np.array([[1, 2], [3, 4]])  # Matriz de 2x2
vector = np.array(
    [
        5,
        6,
    ]
)  # Vector de 2x1
result_vector = np.dot(matrix, vector)
print("Matriz por vector:\n", result_vector)

# La multiplicación se puede hacer si el número de columnas de la primera matriz es igual al número de filas de la segunda matriz.

Matriz por vector:
 [17 39]


### Multiplicación entre matrices*

In [20]:
# Crear dos matrices
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

# Multiplicación de matrices
resultado = np.dot(matriz1, matriz2)  # Multiplicación de matrices
print("Matriz 1:")
print(matriz1)
print("Matriz 2:")
print(matriz2)
print("Multiplicación de Matrices:")
print(resultado)

# La multiplicación se puede hacer si el número de columnas de la primera matriz es igual al número de filas de la segunda matriz.

Matriz 1:
[[1 2]
 [3 4]]
Matriz 2:
[[5 6]
 [7 8]]
Multiplicación de Matrices:
[[19 22]
 [43 50]]


In [22]:
# Crear dos matrices
matrizA = np.array([[1, 3], [2, 4], [2, 5]])  # Matriz de 3x2
matrizB = np.array([[1, 3, 2, 2], [2, 4, 5, 1]])  # Matriz de 2x4

# Se observa que el número de columnas de la matriz A es igual al número de filas de la matriz B.
# Multiplicación de matrices
resultado = np.dot(matrizA, matrizB)
print("Matriz A:")
print(matrizA)
print("Matriz B:")
print(matrizB)
print("Multiplicación de Matrices:")
print(resultado)

Matriz A:
[[1 3]
 [2 4]
 [2 5]]
Matriz B:
[[1 3 2 2]
 [2 4 5 1]]
Multiplicación de Matrices:
[[ 7 15 17  5]
 [10 22 24  8]
 [12 26 29  9]]


### Potencia de matrices

In [23]:
# Potencia de matriz
matrix = np.array([[1, 2], [3, 4]])  # Matriz de 2x2
power = 2
result_matrix = np.linalg.matrix_power(matrix, power)  # Matriz elevada a la potencia 2
print("Matriz elevada a la potencia 2:\n", result_matrix)

Matriz elevada a la potencia 2:
 [[ 7 10]
 [15 22]]


### Transposición de matrices

In [24]:
# Transposición de matriz
matrix = np.array([[1, 2], [3, 4]])  # Matriz de 2x2
transposed_matrix = np.transpose(matrix)  # Transposición de la matriz
print("Matriz original:\n", matrix)
print("Matriz transpuesta:\n", transposed_matrix)

Matriz original:
 [[1 2]
 [3 4]]
Matriz transpuesta:
 [[1 3]
 [2 4]]


## Matriz Inversa

In [27]:
# Inversa de matriz
matrix = np.array([[3, 2], [1, 4]])  # Matriz de 2x2
inv_matrix = np.linalg.inv(matrix)  # Inversa de la matriz
print("Matriz original:\n", inv_matrix)

Matriz original:
 [[ 0.4 -0.2]
 [-0.1  0.3]]


In [28]:
# Inversa de matriz
matrix = np.array([[3, 2, 5], [1, 2, 4], [-1, -2, 2]])  # Matriz de 3x3
inv_matrix = np.linalg.inv(matrix)  # Inversa de la matriz
print("Matriz original:\n", inv_matrix)

Matriz original:
 [[ 0.5        -0.58333333 -0.08333333]
 [-0.25        0.45833333 -0.29166667]
 [ 0.          0.16666667  0.16666667]]


## Propiedades de una matriz: la diagonal

Las matrices diagonales tienen todos los elementos fuera de la diagonal igual a cero.

In [30]:
# Matriz diagonal
diagonal_matrix = np.diag([1, 2, 3, 4])  # Matriz diagonal
print("Matriz diagonal:\n", diagonal_matrix)

Matriz diagonal:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## Matrices especiales

### Matriz identidad

In [31]:
# Matriz identidad
identity_matrix = np.identity(3)  # Matriz identidad de 3x3
print("Matriz identidad:\n", identity_matrix)

Matriz identidad:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Matriz cero

In [32]:
# Matriz cero
zero_matrix = np.zeros((2, 2))  # Matriz de ceros de 2x2
print("Matriz cero:\n", zero_matrix)

Matriz cero:
 [[0. 0.]
 [0. 0.]]


### Matrices triangulares

In [34]:
# Matriz triangular superior
matriz_superior = np.array(
    [[1, 2, 3], [0, 4, 5], [0, 0, 6]]
)  # Matriz triangular superior
print("Matriz triangular superior:")
print(matriz_superior)

# Matriz triangular inferior
matriz_inferior = np.array(
    [[1, 0, 0], [4, 5, 0], [7, 8, 9]]
)  # Matriz triangular inferior
print("Matriz triangular inferior:")
print(matriz_inferior)

Matriz triangular superior:
[[1 2 3]
 [0 4 5]
 [0 0 6]]
Matriz triangular inferior:
[[1 0 0]
 [4 5 0]
 [7 8 9]]


## Matrices dispersas

Las matrices dispersas son de gran importancia en diversas aplicaciones y campos debido a que permiten ahorrar memoria y mejorar la eficiencia computacional cuando se trabaja con conjuntos de datos en los que la mayoría de los elementos son ceros.

La elección del formato de representación de matrices dispersas depende en gran medida del tipo de datos y del tipo de operaciones que se realizarán con ellas en una aplicación específica. Cada formato tiene sus propias ventajas y desventajas, y su uso depende de los requerimientos de rendimiento y memoria de una aplicación en particular.

En la industria, la elección del formato más utilizado puede variar según el dominio de aplicación. Sin embargo, aquí hay algunas pautas generales:

### Formato COO (Coordinates)

Este formato es útil cuando se está construyendo una matriz dispersa, ya que permite agregar elementos de manera sencilla. Puede ser una elección adecuada para la creación y manipulación de matrices dispersas.

In [37]:
from scipy.sparse import coo_matrix

# Ejemplo de matriz dispersa en formato COO (Coordenadas)
data = np.array([3, 5, 2, 8])
row_indices = np.array([0, 1, 2, 2])  # Índices de las filas
col_indices = np.array([2, 4, 3, 0])  # Índices de las columnas

# Crear una matriz dispersa en formato COO
sparse_matrix_coo = coo_matrix(
    (data, (row_indices, col_indices)), shape=(3, 5)
)  # Matriz dispersa en formato COO
print("Matriz dispersa en formato COO:")
print(sparse_matrix_coo.toarray())

Matriz dispersa en formato COO:
[[0 0 3 0 0]
 [0 0 0 0 5]
 [8 0 0 2 0]]


### Formato CSC (Compressed Sparse Column)

 Este formato suele ser eficiente para operaciones que involucran columnas, como multiplicación de matrices por vectores, resolución de sistemas de ecuaciones lineales, entre otros. Se usa ampliamente en ámbitos como el procesamiento de imágenes y el procesamiento de texto.

In [39]:
from scipy.sparse import csc_matrix

# Ejemplo de matriz dispersa en formato CSC
data = np.array([3, 5, 2, 8])
row_indices = np.array([0, 1, 2, 2])  # Índices de las filas
col_indices = np.array([2, 4, 3, 0])  # Índices de las columnas

sparse_matrix_csc = csc_matrix(
    (data, (row_indices, col_indices)), shape=(3, 5)
)  # Crear una matriz dispersa en formato CSC
print("Matriz dispersa en formato CSC:")
print(sparse_matrix_csc.toarray())

Matriz dispersa en formato CSC:
[[0 0 3 0 0]
 [0 0 0 0 5]
 [8 0 0 2 0]]


### Formato CSR (Compressed Sparse Row)

Similar al formato CSC, es eficiente para operaciones que involucran filas. También se usa comúnmente en aplicaciones relacionadas con datos dispersos.

In [40]:
from scipy.sparse import csr_matrix

# Ejemplo de matriz dispersa en formato CSR (Compressed Sparse Row)
data = np.array([4, 1, 7])
row_ptr = np.array([0, 1, 2, 3])  # Punteros de las filas
col_indices = np.array([0, 1, 3])  # Índices de las columnas

# Crear una matriz dispersa en formato CSR
sparse_matrix_csr = csr_matrix(
    (data, col_indices, row_ptr), shape=(3, 5)
)  # Matriz dispersa en formato CSR
print("\nMatriz dispersa en formato CSR:")
print(sparse_matrix_csr.toarray())


Matriz dispersa en formato CSR:
[[4 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 7 0]]


### Formato LIL (List of List)

El formato LIL es útil cuando se necesita una construcción incremental de matrices dispersas. Puede ser una elección razonable en aplicaciones donde la matriz se crea paso a paso.

In [43]:
from scipy.sparse import lil_matrix

# Ejemplo de matriz dispersa en formato LIL
sparse_matrix_lil = lil_matrix((3, 5))  # Crear una matriz dispersa en formato LIL

# Rellenar la matriz dispersa LIL
sparse_matrix_lil[0, 2] = 3  # Asignar un valor en la posición (0, 2)
sparse_matrix_lil[1, 4] = 5  # Asignar un valor en la posición (1, 4)
sparse_matrix_lil[2, 3] = 2  # Asignar un valor en la posición (2, 3)
sparse_matrix_lil[2, 0] = 8  # Asignar un valor en la posición (2, 0)

print("\nMatriz dispersa en formato LIL:")
print(sparse_matrix_lil.toarray())


Matriz dispersa en formato LIL:
[[0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 5.]
 [8. 0. 0. 2. 0.]]


### Formato DOK (Dictionary of Keys)

Similar al formato LIL, DOK es útil para la construcción incremental de matrices. Es eficiente para establecer elementos individuales y puede ser adecuado en aplicaciones con una construcción esparcida incremental.

In [44]:
from scipy.sparse import dok_matrix

# Ejemplo de matriz dispersa en formato DOK
sparse_matrix_dok = dok_matrix((3, 5))  # Crear una matriz dispersa en formato DOK

# Rellenar la matriz dispersa DOK
sparse_matrix_dok[0, 2] = 3  # Asignar un valor en la posición (0, 2)
sparse_matrix_dok[1, 4] = 5  # Asignar un valor en la posición (1, 4)
sparse_matrix_dok[2, 3] = 2  # Asignar un valor en la posición (2, 3)
sparse_matrix_dok[2, 0] = 8  # Asignar un valor en la posición (2, 0)

print("\nMatriz dispersa en formato DOK:")
print(sparse_matrix_dok.toarray())


Matriz dispersa en formato DOK:
[[0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 5.]
 [8. 0. 0. 2. 0.]]
